/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module good_counter(clk, reset, cnt);
  wire [1:0] _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  input clk;
  wire clk;
  output [1:0] cnt;
  reg [1:0] cnt;
  input reset;
  wire reset;
  sky130_fd_sc_hd__nor2_1 _5_ (
    .A(_4_),
    .B(_3_),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nor2b_1 _6_ (
    .A(_4_),
    .B_N(_3_),
    .Y(_2_)
  );
  always @(posedge clk, posedge reset)
    if (reset) cnt[0] <= 1'h0;
    else cnt[0] <= _0_[0];
  always @(posedge clk, posedge reset)
    if (reset) cnt[1] <= 1'h0;
    else cnt[1] <= _0_[1];
  assign _4_ = cnt[1];
  assign _3_ = cnt[0];
  assign _0_[0] = _1_;
  assign _0_[1] = _2_;
endmodule
